repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
      - id: check-added-large-files
  - repo: https://github.com/jumanjihouse/pre-commit-hooks.git
    rev: 2.1.5
    hooks:
      - id: shellcheck
        args: ['--shell=bash', '--color=always', '--external-sources']
        additional_dependencies: []
  - repo: local
    hooks:
      - id: prettier
        name: prettier
        entry: npx prettier --write --list-different --ignore-unknown
        language: system
        pass_filenames: true
        types: [text]
        args: []
        require_serial: false
      - id: eslint
        name: eslint
        entry: npx eslint
        language: system
        pass_filenames: true
        types_or: [ts, javascript]
        args: []
        require_serial: false
  - repo: local
    hooks:
      - id: tests
        name: Mocha tests
        language: system
        entry: npm test
        always_run: true
        pass_filenames: false
        require_serial: true
  - repo: local
    hooks:
      - id: coverage
        name: Ensure that coverage hasn't decreased per-file
        language: system
        entry: ./check-coverage last-coverage-summary.json
        always_run: true
        pass_filenames: false
        require_serial: true
  - repo: local
    hooks:
      - id: svelte-check
        name: Svelte check
        language: system
        entry: npx svelte-check --fail-on-warnings
        always_run: true
        pass_filenames: false
        require_serial: true
  - repo: local
    hooks:
      - id: rollup
        name: Rollup dry run
        language: system
        entry: sh -c 'ADDON_DIST_DIR="$(mktemp -d)"; export ADDON_DIST_DIR; npm run build; EXITCODE=$?; rm -r "${ADDON_DIST_DIR}"; exit "${EXITCODE}"'
        always_run: true
        pass_filenames: false
        require_serial: true
