#!/bin/bash
OUTPUT="$(readlink -f ./build.xpi)"
TEMPDIR="$(mktemp -d)"
rm "${OUTPUT}"
for f in $(git ls-tree -r HEAD --name-only | grep -Ev '^build$|^test/|\.eslintrc\.js|\.gitignore|\.gitmodules|README.md|WE-TODO.md|LICENSE|package.json'; echo lib/css-color-parser/csscolorparser.js); do
    if [ -f "${f}" ]; then
        OUT="${TEMPDIR}/${f}"
        mkdir -p "$(dirname ${OUT})"
        sed '/\/browser-polyfill.min.js/d' "${f}" > "${OUT}"
    fi
done
(
    cd "${TEMPDIR}"
    zip -r "${OUTPUT}" .
)
rm -r "${TEMPDIR}"
