#!/bin/bash
set -ex
if [[ ! -f ./manifest.json || ! -d ./.git ]]; then
    echo 'build script is not launched from add-on root source directory which is not supported'
    exit 1
fi
OUTPUT="$(readlink -f ./build.xpi)"
rm -f "${OUTPUT}"

npx webpack
(
    cd "./dist/"
    zip -r "${OUTPUT}" .
)
